# Site settings
title: KinKinetics
email: kinkinetics@kinkinetics.com
description: "Enhancing astronaut resilience and productivity through innovative emotional and psychological support technologies for long-duration space missions."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.kinkinetics.com" # the base hostname & protocol for your site

twitter_username: KinKinetics
github_username: ""

# Build settings
markdown: kramdown
show_downloads: false
